/**
 * Conteúdo informacional das 11 disciplinas: alimenta a seção "Guia do
 * ciclo básico" da página principal e as páginas dedicadas
 * (/aprova-universitario/<slug>/). Fala do que cada disciplina cobre em
 * geral e de como estudar; não descreve a ementa do curso (pendência:
 * carga horária e módulos vêm do time).
 */

export type DisciplinaGuia = {
  slug: string;
  nome: string;
  foto: string;
  alt: string;
  h1: string;
  metaTitle: string;
  metaDescription: string;
  resumo: string;
  oQueEstuda: string;
  topicos: readonly string[];
  dificuldade: string;
  comoEstudar: string;
  faq: readonly { q: string; a: string }[];
};

export const guia = {
  h2: "Guia do ciclo básico: o que cai em cada disciplina da área da saúde",
  intro: [
    "O ciclo básico é o conjunto de disciplinas dos primeiros períodos de Medicina, Odontologia, Biomedicina, Enfermagem, Fisioterapia, Farmácia, Nutrição, Psicologia e Educação Física. Nele o aluno aprende como o corpo humano é construído (Anatomia, Histologia, Embriologia), como funciona (Fisiologia, Bioquímica), o que dá errado (Patologia), quem ataca o organismo (Microbiologia, Parasitologia), como ele se defende (Imunologia), como a informação é herdada (Genética) e como os medicamentos agem (Farmacologia).",
    "O problema é que essas matérias chegam todas ao mesmo tempo, com volume alto e pouca ligação entre elas. Abaixo, um resumo do que cada disciplina cobre, onde a maioria trava e como estudar com aulas curtas, mapas mentais e questões. Cada disciplina também tem uma página própria com mais detalhes.",
  ],
  verPagina: "Ver a página de",
  outrasDisciplinas: "Outras disciplinas do ciclo básico",
  voltar: "Voltar para a página do Aprova Universitário",
  pill: "Aprova Universitário · Ciclo básico da área da saúde",
  oQueEstudaTitulo: "O que você estuda em",
  topicosTitulo: "Principais temas de",
  dificuldadeTitulo: "Por que {nome} trava tanta gente no início da faculdade",
  comoEstudarTitulo: "Como estudar {nome} com o Aprova Universitário",
  comoEstudarItens: [
    "Videoaulas curtas e visuais, direto ao ponto, para entender em poucos minutos",
    "Mapas mentais prontos para fixar o conteúdo antes da prova",
    "Quizzes com feedback imediato em cada aula",
    "Questões separadas por disciplina, dentro das mais de 2.100 da plataforma",
    "Acompanhamento do progresso na seção Minhas métricas",
    "Acesso pelo celular, no seu ritmo, na hora em que você trava",
  ],
  ofertaTitulo: "Tudo isso, e as outras 10 disciplinas, por",
  faqTitulo: "Perguntas frequentes sobre",
  ctaHero: "Assine agora por R$ 79,00/mês",
  cta: "Assine agora",
} as const;

export const disciplinasGuia: readonly DisciplinaGuia[] = [
  {
    slug: "anatomia",
    nome: "Anatomia",
    foto: "anatomia",
    alt: "Ilustração de Anatomia: corpo humano com o sistema circulatório em destaque",
    h1: "Anatomia para o ciclo básico: aulas curtas e visuais para entender o corpo humano",
    metaTitle: "Anatomia para o Ciclo Básico: aulas curtas e visuais",
    metaDescription: "Curso de Anatomia online para o início da área da saúde: sistemas, planos e termos anatômicos em videoaulas curtas, mapas mentais e questões. R$ 79,00 por mês.",
    resumo: "Estude a estrutura do corpo humano de forma integrada e visual. Ideal para quem precisa visualizar para entender.",
    oQueEstuda: "Anatomia é o estudo da estrutura do corpo humano: ossos, músculos, articulações, vasos, nervos e órgãos, e a forma como tudo isso se organiza em sistemas. No ciclo básico, a disciplina costuma começar pela posição anatômica, pelos planos e eixos e pelos termos de direção, e depois avança sistema por sistema. É a base de quase todas as matérias clínicas: sem saber onde cada estrutura fica e com o que ela se relaciona, fica difícil entender Fisiologia, Patologia e, mais tarde, o exame físico e a cirurgia.",
    topicos: [
      "Posição anatômica, planos, eixos e termos de direção",
      "Sistema esquelético: osteologia do crânio, coluna e membros",
      "Sistema articular e sistema muscular",
      "Sistema cardiovascular: coração, artérias e veias",
      "Sistema respiratório e sistema digestório",
      "Sistema urinário e sistema genital",
      "Sistema nervoso central e periférico",
      "Anatomia topográfica: cabeça e pescoço, tórax, abdome e membros",
    ],
    dificuldade: "Anatomia é a disciplina do volume. São centenas de nomes em latim, muitas estruturas parecidas e pouco tempo de laboratório para fixar cada peça. Quem tenta decorar lista por lista esquece na semana seguinte. O que funciona é visualizar a estrutura, entender a relação dela com as vizinhas e ligar a forma à função.",
    comoEstudar: "No Aprova Universitário, cada tema de Anatomia vira uma videoaula curta, com produção visual que mostra a estrutura em vez de só descrever. Depois da aula, o mapa mental resume o sistema em uma página e o quiz confere se você realmente entendeu antes de seguir. As questões separadas por disciplina servem para treinar no formato da prova.",
    faq: [
      { q: "Anatomia é decoreba?", a: "Tem memorização, mas ela só se sustenta com entendimento. Quando você sabe por que uma artéria passa por determinado lugar e o que ela irriga, o nome deixa de ser um dado solto." },
      { q: "Serve para quem estuda Anatomia sem laboratório?", a: "Sim. As aulas são visuais justamente para quem não tem acesso frequente às peças. Elas mostram as estruturas e as relações entre elas, o que ajuda a aproveitar melhor o laboratório quando ele existe." },
      { q: "Dá para usar junto com o atlas da faculdade?", a: "Dá, e é o ideal. A aula explica a lógica do sistema, o atlas dá o detalhe, e o quiz e as questões mostram o que você já fixou." },
    ],
  },
  {
    slug: "bioquimica",
    nome: "Bioquímica",
    foto: "bioquimica",
    alt: "Ilustração de Bioquímica: estrutura molecular em azul",
    h1: "Bioquímica para o ciclo básico: entenda o metabolismo em vez de decorar vias",
    metaTitle: "Bioquímica para o Ciclo Básico: metabolismo sem decoreba",
    metaDescription: "Aulas de Bioquímica para Medicina e área da saúde: enzimas, glicólise, ciclo de Krebs e integração metabólica em aulas curtas e mapas mentais. R$ 79,00 por mês.",
    resumo: "Aprenda como as reações bioquímicas transformam os nutrientes em energia e compreenda os principais ciclos, enzimas e processos metabólicos do organismo.",
    oQueEstuda: "Bioquímica explica a vida em nível molecular: quais são as moléculas do corpo (carboidratos, lipídios, proteínas e ácidos nucleicos), como as enzimas aceleram as reações e como os nutrientes viram energia. O coração da disciplina é o metabolismo: glicólise, ciclo de Krebs, cadeia respiratória, gliconeogênese, oxidação de ácidos graxos e a forma como esses caminhos se integram no jejum, na alimentação e no exercício.",
    topicos: [
      "Água, pH, tampões e aminoácidos",
      "Estrutura e função das proteínas",
      "Enzimas: cinética, regulação e inibição",
      "Carboidratos: glicólise, glicogênio e gliconeogênese",
      "Ciclo de Krebs e cadeia respiratória",
      "Lipídios: beta-oxidação, cetogênese e colesterol",
      "Metabolismo de aminoácidos e ciclo da ureia",
      "Integração metabólica: jejum, alimentação e exercício",
    ],
    dificuldade: "Bioquímica assusta porque as vias têm muitas etapas, muitos nomes de enzimas e muitos intermediários. Quem estuda cada via isolada, sem saber para que ela serve no corpo, decora hoje e esquece amanhã. A saída é entender a lógica: o que entra, o que sai, onde a via é regulada e o que acontece quando ela falha.",
    comoEstudar: "As videoaulas de Bioquímica do Aprova Universitário contam cada via como uma história, com esquemas visuais que mostram o fluxo em vez de uma tabela de reações. O mapa mental condensa a via em uma página para revisão rápida, e o quiz de cada aula aponta na hora o que ainda não ficou claro.",
    faq: [
      { q: "Preciso decorar todas as enzimas?", a: "Não todas. As provas cobram as enzimas reguladoras, os pontos de controle e os produtos principais. É melhor entender onde cada via é ligada e desligada do que memorizar todos os intermediários." },
      { q: "Bioquímica tem relação com a clínica?", a: "Toda. Diabetes, jejum prolongado, intolerâncias, erros inatos do metabolismo e a ação de vários medicamentos só fazem sentido com Bioquímica." },
      { q: "Consigo estudar Bioquímica pelo celular?", a: "Sim. As aulas são curtas e os mapas mentais foram feitos para revisar em qualquer lugar, inclusive no trajeto para a faculdade." },
    ],
  },
  {
    slug: "fisiologia",
    nome: "Fisiologia",
    foto: "fisiologia",
    alt: "Ilustração de Fisiologia: cérebro e sistema nervoso iluminados",
    h1: "Fisiologia para o ciclo básico: como o corpo funciona, sistema por sistema",
    metaTitle: "Fisiologia para o Ciclo Básico: como o corpo funciona",
    metaDescription: "Aulas de Fisiologia para o início da faculdade: sistemas nervoso, cardiovascular, respiratório e renal com esquemas claros e questões. R$ 79,00 por mês.",
    resumo: "Veja como o corpo funciona de verdade. Entenda os principais mecanismos dos sistemas (nervoso, cardiovascular, respiratório etc.) com esquemas e explicações claras.",
    oQueEstuda: "Se Anatomia mostra as peças, Fisiologia explica como elas funcionam juntas. A disciplina parte da homeostase e da fisiologia celular (membranas, transporte, potencial de ação) e percorre os grandes sistemas: como o coração bombeia e a pressão é regulada, como o pulmão troca gases, como o rim filtra e concentra a urina, como o intestino digere e absorve, como hormônios e sistema nervoso coordenam tudo isso.",
    topicos: [
      "Homeostase, membranas e transporte",
      "Potencial de repouso, potencial de ação e sinapses",
      "Fisiologia cardiovascular: ciclo cardíaco, débito e pressão arterial",
      "Fisiologia respiratória: ventilação, trocas gasosas e controle da respiração",
      "Fisiologia renal: filtração, reabsorção e equilíbrio hidroeletrolítico",
      "Fisiologia digestória: motilidade, secreção e absorção",
      "Fisiologia endócrina e neurofisiologia",
      "Fisiologia do músculo esquelético, cardíaco e liso",
    ],
    dificuldade: "Fisiologia exige integrar mecanismos e interpretar gráficos e curvas. O aluno entende cada pedaço isolado, mas se perde quando a prova pergunta o que acontece com a pressão arterial se o volume cai, ou como o rim responde a uma acidose. Sem um fio condutor, vira um monte de regras desconexas.",
    comoEstudar: "No Aprova Universitário, cada mecanismo de Fisiologia é explicado com esquemas animados que mostram causa e consequência. O mapa mental organiza o sistema inteiro em uma página, o quiz confere o raciocínio e as questões treinam exatamente o tipo de integração que a prova cobra.",
    faq: [
      { q: "Fisiologia é mais difícil que Anatomia?", a: "É diferente. Anatomia pede memória visual; Fisiologia pede raciocínio. Muitos alunos acham Fisiologia mais interessante quando param de decorar e passam a entender os mecanismos." },
      { q: "Preciso saber Bioquímica antes?", a: "Ajuda, principalmente em fisiologia celular, endócrina e do exercício. Se você estiver cursando as duas ao mesmo tempo, dá para estudar em paralelo." },
      { q: "As aulas cobrem os gráficos que caem em prova?", a: "Sim. Curvas de pressão e volume, dissociação da hemoglobina e potencial de ação são explicados passo a passo." },
    ],
  },
  {
    slug: "histologia",
    nome: "Histologia",
    foto: "histologia",
    alt: "Ilustração de Histologia: microscópio sobre uma lâmina de tecido",
    h1: "Histologia para o ciclo básico: reconheça os tecidos ao microscópio",
    metaTitle: "Histologia para o Ciclo Básico: tecidos e lâminas",
    metaDescription: "Aulas de Histologia para a área da saúde: tecidos epitelial, conjuntivo, muscular e nervoso, lâminas e colorações em videoaulas visuais. R$ 79,00 por mês.",
    resumo: "Aprenda a identificar os tecidos do corpo em nível microscópico. Entenda como as células se organizam para formar os tecidos que compõem os órgãos e como essa organização se relaciona com as funções fisiológicas.",
    oQueEstuda: "Histologia estuda os tecidos: como as células se agrupam, que matriz produzem e como essa organização sustenta a função de cada órgão. A disciplina começa pelos quatro tecidos fundamentais (epitelial, conjuntivo, muscular e nervoso) e depois aplica esse conhecimento aos sistemas, na chamada histologia dos órgãos. Boa parte da avaliação é prática: reconhecer estruturas em lâminas coradas.",
    topicos: [
      "Métodos de estudo: preparo de lâminas, colorações e microscopia",
      "Tecido epitelial de revestimento e glandular",
      "Tecido conjuntivo, adiposo, cartilaginoso e ósseo",
      "Tecido muscular esquelético, cardíaco e liso",
      "Tecido nervoso",
      "Sangue e hematopoese",
      "Histologia dos sistemas: circulatório, respiratório, digestório, urinário e genital",
      "Pele e anexos",
    ],
    dificuldade: "O problema de Histologia é o olho: no começo, todas as lâminas parecem iguais. O aluno lê a teoria, mas não consegue apontar na imagem o que está lendo. Sem repetição visual guiada, a prova prática vira sorte.",
    comoEstudar: "As videoaulas de Histologia do Aprova Universitário são construídas em cima das imagens: cada tecido é mostrado, apontado e comparado com os parecidos. Os mapas mentais resumem as características que diferenciam um tecido do outro, e os quizzes treinam o reconhecimento antes da prova prática.",
    faq: [
      { q: "Como estudar para a prova prática de lâminas?", a: "Vendo imagens muitas vezes, com alguém apontando o que olhar. É isso que as aulas fazem: mostram a lâmina, destacam as estruturas e comparam com tecidos parecidos." },
      { q: "Histologia é pré-requisito para Patologia?", a: "Na prática, sim. Patologia descreve o tecido doente; para reconhecer a alteração, você precisa saber como é o tecido normal." },
      { q: "As aulas usam as colorações comuns da faculdade?", a: "Sim. O foco é a hematoxilina e eosina, que é a base das provas, com menção às colorações especiais quando fazem diferença." },
    ],
  },
  {
    slug: "patologia",
    nome: "Patologia",
    foto: "patologia",
    alt: "Ilustração de Patologia: células alteradas vistas em microscopia",
    h1: "Patologia para o ciclo básico: lesão celular, inflamação e neoplasia sem sofrimento",
    metaTitle: "Patologia para o Ciclo Básico: inflamação e lesão celular",
    metaDescription: "Aulas de Patologia geral: adaptações celulares, necrose, inflamação, reparo e neoplasias com correlação clínica, mapas mentais e questões. R$ 79,00 por mês.",
    resumo: "Veja o que pode acontecer quando algo dá errado no corpo. Foco em inflamações, lesões, necroses e adaptações celulares, sempre com relação à prática clínica.",
    oQueEstuda: "Patologia geral explica os mecanismos comuns das doenças: como a célula se adapta ao estresse (hipertrofia, hiperplasia, atrofia, metaplasia), como ela se lesa e morre (necrose e apoptose), como o corpo responde com inflamação e reparo, o que são os distúrbios da circulação (edema, trombose, embolia, infarto) e como surgem as neoplasias. É a ponte entre o ciclo básico e a clínica.",
    topicos: [
      "Adaptações celulares: hipertrofia, hiperplasia, atrofia e metaplasia",
      "Lesão celular reversível e irreversível, necrose e apoptose",
      "Acúmulos intracelulares e calcificações",
      "Inflamação aguda e crônica",
      "Reparo, regeneração e cicatrização",
      "Distúrbios hemodinâmicos: edema, hemorragia, trombose, embolia e infarto",
      "Neoplasias: nomenclatura, características e carcinogênese",
      "Introdução à patologia dos sistemas",
    ],
    dificuldade: "Patologia mistura vocabulário novo com raciocínio de causa e efeito. O aluno aprende o que é uma metaplasia, mas não sabe dizer por que ela aparece no esôfago de quem tem refluxo. Sem a correlação clínica, os termos ficam soltos e a prova cobra justamente a ligação entre eles.",
    comoEstudar: "No Aprova Universitário, cada tema de Patologia é apresentado a partir do que acontece na célula e ligado a um exemplo clínico. Os mapas mentais organizam as classificações (tipos de necrose, fases da inflamação, critérios de malignidade) e os quizzes e questões treinam o raciocínio que a prova pede.",
    faq: [
      { q: "Patologia geral e Patologia especial são a mesma coisa?", a: "Não. A geral estuda os mecanismos comuns a todas as doenças, e é o que cai no ciclo básico. A especial aplica esses mecanismos a cada órgão e costuma vir depois." },
      { q: "Preciso saber Histologia antes?", a: "Ajuda muito. Patologia descreve a alteração do tecido; conhecer o tecido normal é o ponto de partida." },
      { q: "As aulas mostram lâminas de Patologia?", a: "Sim, quando a imagem ajuda a entender o conceito, como nos tipos de necrose e nas neoplasias." },
    ],
  },
  {
    slug: "microbiologia",
    nome: "Microbiologia",
    foto: "microbiologia",
    alt: "Ilustração de Microbiologia: bactérias e micro-organismos",
    h1: "Microbiologia para o ciclo básico: bactérias, vírus e fungos explicados de forma clara",
    metaTitle: "Microbiologia para o Ciclo Básico: bactérias, vírus e fungos",
    metaDescription: "Curso de Microbiologia online: estrutura bacteriana, Gram, vírus, fungos, antimicrobianos e resistência em aulas curtas e mapas mentais. R$ 79,00 por mês.",
    resumo: "Entenda as principais características de vírus, bactérias e fungos e compreenda como esses agentes infecciosos atuam no organismo e impactam sua saúde.",
    oQueEstuda: "Microbiologia estuda os micro-organismos que interessam à saúde: bactérias, vírus e fungos. A disciplina cobre a estrutura e o metabolismo bacteriano, a classificação pelo Gram, os mecanismos de patogenicidade, a replicação viral, os fungos de importância médica e os antimicrobianos, incluindo o problema da resistência. Também entra a microbiota normal e os métodos de diagnóstico em laboratório.",
    topicos: [
      "Estrutura da célula bacteriana e coloração de Gram",
      "Crescimento, metabolismo e genética bacteriana",
      "Mecanismos de patogenicidade e fatores de virulência",
      "Principais bactérias de importância médica",
      "Vírus: estrutura, replicação e principais famílias",
      "Fungos: micoses superficiais, subcutâneas e sistêmicas",
      "Antibióticos, antivirais e antifúngicos",
      "Resistência antimicrobiana e controle de infecção",
    ],
    dificuldade: "Em Microbiologia, o volume vem em forma de lista: dezenas de agentes, cada um com estrutura, doença, diagnóstico e tratamento. Estudar agente por agente, sem um sistema de comparação, deixa tudo parecido e a prova explora exatamente as diferenças.",
    comoEstudar: "As videoaulas de Microbiologia do Aprova Universitário agrupam os agentes por características e mostram o que diferencia cada um. Os mapas mentais funcionam como tabelas comparativas em uma página, e os quizzes treinam o reconhecimento rápido que as provas cobram.",
    faq: [
      { q: "Microbiologia e Parasitologia são a mesma matéria?", a: "Não. Microbiologia cuida de bactérias, vírus e fungos; Parasitologia, de protozoários e helmintos. Em algumas faculdades elas são dadas juntas, mas o conteúdo é diferente." },
      { q: "Preciso decorar todas as bactérias?", a: "Não. As provas concentram nos agentes de maior importância médica. As aulas priorizam esses e ensinam a comparar." },
      { q: "As aulas falam de antibióticos?", a: "Sim, com foco em mecanismo de ação e nos principais grupos. O detalhamento clínico vem depois, em Farmacologia e Infectologia." },
    ],
  },
  {
    slug: "imunologia",
    nome: "Imunologia",
    foto: "imunologia",
    alt: "Ilustração de Imunologia: anticorpos atacando um vírus",
    h1: "Imunologia para o ciclo básico: entenda as defesas do corpo sem se perder nas siglas",
    metaTitle: "Imunologia para o Ciclo Básico: imunidade inata e adaptativa",
    metaDescription: "Aulas de Imunologia para iniciantes: imunidade inata e adaptativa, linfócitos, anticorpos, MHC e vacinas em videoaulas curtas e questões. R$ 79,00 por mês.",
    resumo: "Aprenda como funciona o sistema imunológico e saiba identificar os diferentes tipos de imunidade que protegem o nosso corpo.",
    oQueEstuda: "Imunologia explica como o corpo reconhece e combate o que é estranho. A disciplina parte da imunidade inata (barreiras, fagócitos, complemento, inflamação) e chega à imunidade adaptativa (linfócitos T e B, anticorpos, apresentação de antígeno pelo MHC). Depois aplica isso a vacinas, hipersensibilidades, autoimunidade, imunodeficiências e transplantes.",
    topicos: [
      "Imunidade inata: barreiras, fagócitos e sistema complemento",
      "Órgãos linfoides e células do sistema imune",
      "Antígenos, anticorpos e classes de imunoglobulinas",
      "Apresentação de antígeno e MHC",
      "Linfócitos T e B: ativação, diferenciação e memória",
      "Vacinas e imunização",
      "Hipersensibilidades tipos I a IV",
      "Autoimunidade, imunodeficiências e transplantes",
    ],
    dificuldade: "Imunologia é a disciplina das siglas e das cascatas: CD4, CD8, MHC, IL-2, IgG, C3b. O aluno decora os nomes, mas não vê a sequência dos eventos. Como tudo acontece ao mesmo tempo e em vários lugares, sem um esquema visual a matéria parece não ter começo nem fim.",
    comoEstudar: "No Aprova Universitário, cada resposta imune é contada em ordem, com esquemas que mostram quem chama quem. Os mapas mentais organizam as células, as moléculas e os tipos de resposta em uma página, e os quizzes verificam se a sequência ficou clara antes de avançar.",
    faq: [
      { q: "Por onde começar em Imunologia?", a: "Pela imunidade inata e pelas células do sistema imune. Sem isso, a imunidade adaptativa não faz sentido." },
      { q: "Imunologia cai muito na prova?", a: "Cai no ciclo básico e volta em Infectologia, Reumatologia, Alergia e Oncologia. É uma base que compensa fixar bem." },
      { q: "As aulas explicam as hipersensibilidades?", a: "Sim, os quatro tipos com exemplos clínicos, que é como as provas costumam cobrar." },
    ],
  },
  {
    slug: "genetica",
    nome: "Genética",
    foto: "genetica",
    alt: "Ilustração de Genética: fita de DNA em azul",
    h1: "Genética para o ciclo básico: do DNA aos padrões de herança",
    metaTitle: "Genética para o Ciclo Básico: do DNA aos heredogramas",
    metaDescription: "Aulas de Genética para a área da saúde: replicação, transcrição, mutações, herança mendeliana e cromossomopatias em aulas curtas. R$ 79,00 por mês.",
    resumo: "Genética vai muito além do DNA. Entenda como variações no nosso genótipo podem impactar o funcionamento do organismo.",
    oQueEstuda: "Genética estuda como a informação biológica é guardada, copiada, lida e herdada. A disciplina cobre a estrutura do DNA, replicação, transcrição e tradução, as mutações e seus efeitos, os padrões de herança (autossômica dominante e recessiva, ligada ao X, mitocondrial), as alterações cromossômicas e as bases da genética de populações e do aconselhamento genético.",
    topicos: [
      "Estrutura do DNA, cromatina e cromossomos",
      "Replicação, transcrição e tradução",
      "Regulação da expressão gênica",
      "Mutações e reparo do DNA",
      "Herança mendeliana e heredogramas",
      "Herança ligada ao sexo, mitocondrial e multifatorial",
      "Cromossomopatias: síndromes de Down, Turner e Klinefelter",
      "Genética de populações e aconselhamento genético",
    ],
    dificuldade: "Genética junta biologia molecular com probabilidade. Muitos alunos dominam a teoria do DNA, mas travam nos heredogramas e nos cálculos de risco, ou o contrário. Como as duas partes caem na mesma prova, a nota depende de fechar as duas.",
    comoEstudar: "As videoaulas de Genética do Aprova Universitário separam a parte molecular da parte de herança e dão exemplos resolvidos de heredograma passo a passo. Os mapas mentais resumem os padrões de herança com suas características, e os quizzes treinam a leitura de heredogramas até virar automática.",
    faq: [
      { q: "Preciso saber muita matemática?", a: "Só probabilidade básica: multiplicar e somar chances. As aulas mostram o raciocínio em cima de exemplos." },
      { q: "Genética do ciclo básico é igual à do Enem?", a: "A base é a mesma, mas a faculdade aprofunda em biologia molecular, cromossomopatias e aconselhamento genético." },
      { q: "As aulas cobrem cromossomopatias?", a: "Sim, com as síndromes mais cobradas e o mecanismo por trás de cada uma." },
    ],
  },
  {
    slug: "parasitologia",
    nome: "Parasitologia",
    foto: "parasitologia",
    alt: "Ilustração de Parasitologia: parasita visto ao microscópio",
    h1: "Parasitologia para o ciclo básico: ciclos, transmissão e prevenção sem decoreba",
    metaTitle: "Parasitologia para o Ciclo Básico: ciclos e transmissão",
    metaDescription: "Aulas de Parasitologia: protozoários, helmintos, ciclos de vida, vetores e profilaxia em videoaulas curtas, mapas mentais e questões. R$ 79,00 por mês.",
    resumo: "Estude os principais parasitas que afetam os seres humanos e as doenças que eles causam. Aprenda a reconhecer, prevenir e compreender as infecções parasitárias mais comuns.",
    oQueEstuda: "Parasitologia estuda os protozoários e os helmintos que causam doença em humanos, além dos artrópodes que transmitem parte deles. Para cada parasita, a disciplina cobre a morfologia, o ciclo de vida, a forma de transmissão, a doença que causa, o diagnóstico e a prevenção. Doença de Chagas, malária, leishmanioses, toxoplasmose, giardíase, ascaridíase, esquistossomose e teníase são exemplos centrais.",
    topicos: [
      "Conceitos: parasitismo, hospedeiros, vetores e ciclos de vida",
      "Protozoários intestinais: Giardia e Entamoeba",
      "Protozoários do sangue e tecidos: Plasmodium, Trypanosoma cruzi, Leishmania e Toxoplasma",
      "Helmintos intestinais: Ascaris, ancilostomídeos, Enterobius e Strongyloides",
      "Cestódeos: Taenia e cisticercose",
      "Trematódeos: Schistosoma mansoni",
      "Artrópodes de interesse médico",
      "Diagnóstico laboratorial e profilaxia",
    ],
    dificuldade: "Cada parasita tem um ciclo com hospedeiros, formas evolutivas e vias de entrada diferentes. Estudar ciclo por ciclo, em texto, confunde: qual forma é infectante, qual é diagnóstica, onde o vetor entra. A prova cobra justamente essas etapas.",
    comoEstudar: "No Aprova Universitário, cada ciclo de vida é mostrado em esquema visual, com as formas evolutivas destacadas e a etapa de transmissão marcada. Os mapas mentais comparam os parasitas parecidos lado a lado, e os quizzes treinam a diferenciação que as provas cobram.",
    faq: [
      { q: "Qual a diferença entre protozoário e helminto?", a: "Protozoários são unicelulares (Giardia, Plasmodium); helmintos são vermes multicelulares (Ascaris, Taenia). Os ciclos e os tratamentos são diferentes." },
      { q: "Parasitologia cai muito em concursos depois?", a: "Cai, principalmente nas doenças endêmicas no Brasil, como Chagas, malária, leishmaniose e esquistossomose. Fixar agora poupa tempo depois." },
      { q: "As aulas mostram as formas ao microscópio?", a: "Sim, cistos, ovos e trofozoítos são mostrados quando importam para o diagnóstico." },
    ],
  },
  {
    slug: "farmacologia",
    nome: "Farmacologia",
    foto: "farmacologia",
    alt: "Ilustração de Farmacologia: cápsula de medicamento com partículas",
    h1: "Farmacologia para o ciclo básico: como os medicamentos agem no corpo",
    metaTitle: "Farmacologia Básica: como os medicamentos agem no corpo",
    metaDescription: "Aulas de Farmacologia básica: farmacocinética, farmacodinâmica, receptores, vias de administração e reações adversas em aulas curtas. R$ 79,00 por mês.",
    resumo: "Entenda como os medicamentos agem no corpo, explorando os princípios de farmacocinética, farmacodinâmica e os possíveis efeitos adversos das diferentes classes farmacológicas.",
    oQueEstuda: "Farmacologia estuda o que o corpo faz com o medicamento (farmacocinética: absorção, distribuição, metabolismo e excreção) e o que o medicamento faz com o corpo (farmacodinâmica: receptores, agonistas, antagonistas, dose e efeito). Com essa base, a disciplina apresenta as primeiras classes de fármacos, em geral as do sistema nervoso autônomo, os anti-inflamatórios e os antimicrobianos, sempre ligando mecanismo, uso e reações adversas.",
    topicos: [
      "Farmacocinética: absorção, distribuição, metabolismo e excreção",
      "Vias de administração e biodisponibilidade",
      "Farmacodinâmica: receptores, agonistas, antagonistas e curvas dose-resposta",
      "Interações medicamentosas e reações adversas",
      "Farmacologia do sistema nervoso autônomo",
      "Anti-inflamatórios, analgésicos e corticoides",
      "Introdução aos antimicrobianos",
      "Princípios de prescrição e segurança do paciente",
    ],
    dificuldade: "Farmacologia exige juntar Fisiologia com uma lista enorme de nomes. Quando o aluno decora o fármaco sem entender o receptor e a via, esquece rápido e não consegue prever efeito nem reação adversa. A prova, por sua vez, cobra exatamente o mecanismo.",
    comoEstudar: "As videoaulas de Farmacologia do Aprova Universitário partem do mecanismo: qual receptor, qual efeito, qual consequência. Os mapas mentais organizam cada classe com seus representantes, usos e reações adversas em uma página, e os quizzes treinam a associação entre mecanismo e efeito.",
    faq: [
      { q: "Preciso decorar nomes comerciais?", a: "Não. As provas usam o nome do princípio ativo e cobram mecanismo, uso principal e reações adversas." },
      { q: "Farmacologia do ciclo básico é a mesma da clínica?", a: "A base é a mesma. No ciclo básico o foco é em princípios gerais e nas primeiras classes; na clínica, o uso em cada doença." },
      { q: "As aulas ajudam com o sistema nervoso autônomo?", a: "Sim. É um dos temas mais cobrados e as aulas o tratam com esquemas de receptores e efeitos." },
    ],
  },
  {
    slug: "embriologia",
    nome: "Embriologia",
    foto: "embriologia",
    alt: "Ilustração de Embriologia: embrião humano em desenvolvimento",
    h1: "Embriologia para o ciclo básico: o desenvolvimento humano semana a semana",
    metaTitle: "Embriologia Humana: desenvolvimento semana a semana",
    metaDescription: "Aulas de Embriologia humana: gametogênese, fecundação, gastrulação, neurulação e formação dos sistemas em videoaulas visuais e questões. R$ 79,00 por mês.",
    resumo: "Entenda o desenvolvimento humano desde a gametogênese até a formação dos sistemas orgânicos.",
    oQueEstuda: "Embriologia acompanha o desenvolvimento humano da formação dos gametas até o nascimento. A disciplina cobre gametogênese, fecundação, clivagem e implantação, a formação dos três folhetos na gastrulação, a neurulação, a dobradura do embrião e a origem de cada sistema, além dos anexos (placenta, cordão umbilical, membranas) e das principais malformações congênitas.",
    topicos: [
      "Gametogênese: espermatogênese e ovogênese",
      "Fecundação, clivagem e implantação",
      "Gastrulação e formação dos folhetos embrionários",
      "Neurulação e dobramento do embrião",
      "Período embrionário e período fetal",
      "Placenta, cordão umbilical e membranas fetais",
      "Desenvolvimento dos sistemas: cardiovascular, nervoso, digestório e urogenital",
      "Malformações congênitas e teratógenos",
    ],
    dificuldade: "Embriologia acontece em três dimensões e ao longo do tempo, mas o aluno estuda por figuras estáticas. É difícil visualizar como o disco embrionário dobra, de onde vem cada estrutura e por que uma falha em determinada semana gera uma malformação específica.",
    comoEstudar: "No Aprova Universitário, as videoaulas de Embriologia mostram o desenvolvimento em movimento, semana a semana, com destaque para a origem de cada estrutura. Os mapas mentais organizam os folhetos e seus derivados, e os quizzes verificam se a sequência temporal ficou clara.",
    faq: [
      { q: "Embriologia é pré-requisito para Anatomia?", a: "Elas se complementam. Entender de onde vem cada estrutura ajuda a lembrar a posição e as relações dela na Anatomia." },
      { q: "O que mais cai em prova de Embriologia?", a: "Gastrulação, derivados dos folhetos, anexos embrionários e as malformações mais comuns, com a semana em que ocorrem." },
      { q: "As aulas cobrem o desenvolvimento de cada sistema?", a: "Sim, com foco nos sistemas mais cobrados: cardiovascular, nervoso, digestório e urogenital." },
    ],
  },
];

export function disciplinaPorSlug(slug: string): DisciplinaGuia | undefined {
  return disciplinasGuia.find((d) => d.slug === slug);
}
